-- =====================================================
-- Styra Safe Migration (idempotent) v4
-- Tables + columns + PKs + uniques + indexes + FKs
-- =====================================================

-- Table: User
CREATE TABLE IF NOT EXISTS "User" (
    "__tmp" TEXT
);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatar" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'CUSTOMER';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isBanned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "banReason" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tokenVersion" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "location" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "preferences" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "protectionPlan" TEXT NOT NULL DEFAULT 'basic';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'User' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "User" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "User" DROP COLUMN IF EXISTS "__tmp";

-- Table: Business
CREATE TABLE IF NOT EXISTS "Business" (
    "__tmp" TEXT
);
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "ownerId" TEXT NOT NULL;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "logo" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "coverImage" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "isVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "operatingHours" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "amenities" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Business' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Business" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Business" DROP COLUMN IF EXISTS "__tmp";

-- Table: Service
CREATE TABLE IF NOT EXISTS "Service" (
    "__tmp" TEXT
);
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "price" DOUBLE PRECISION NOT NULL;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "duration" INTEGER NOT NULL;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Service' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Service" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Service" DROP COLUMN IF EXISTS "__tmp";

-- Table: Staff
CREATE TABLE IF NOT EXISTS "Staff" (
    "__tmp" TEXT
);
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "role" TEXT;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "avatar" TEXT;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Staff' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Staff" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Staff" DROP COLUMN IF EXISTS "__tmp";

-- Table: PortfolioItem
CREATE TABLE IF NOT EXISTS "PortfolioItem" (
    "__tmp" TEXT
);
ALTER TABLE "PortfolioItem" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PortfolioItem" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "PortfolioItem" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "PortfolioItem" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "PortfolioItem" ADD COLUMN IF NOT EXISTS "image" TEXT NOT NULL;
ALTER TABLE "PortfolioItem" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PortfolioItem' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PortfolioItem" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PortfolioItem" DROP COLUMN IF EXISTS "__tmp";

-- Table: Booking
CREATE TABLE IF NOT EXISTS "Booking" (
    "__tmp" TEXT
);
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "customerId" TEXT NOT NULL;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "serviceId" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "staffId" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "time" TEXT NOT NULL;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "endTime" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "totalPrice" DOUBLE PRECISION NOT NULL;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "customerPhone" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "customerEmail" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "staffName" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "serviceName" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "servicePrice" DOUBLE PRECISION;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "disputeReason" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "disputeResolvedAt" TIMESTAMP(3);
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3);
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "cancellationReason" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "confirmedAt" TIMESTAMP(3);
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Booking' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Booking" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Booking" DROP COLUMN IF EXISTS "__tmp";

-- Table: Review
CREATE TABLE IF NOT EXISTS "Review" (
    "__tmp" TEXT
);
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "bookingId" TEXT NOT NULL;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "customerId" TEXT NOT NULL;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "rating" INTEGER NOT NULL;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "comment" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Review' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Review" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Review" DROP COLUMN IF EXISTS "__tmp";

-- Table: Favorite
CREATE TABLE IF NOT EXISTS "Favorite" (
    "__tmp" TEXT
);
ALTER TABLE "Favorite" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Favorite" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Favorite" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "Favorite" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Favorite' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Favorite" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Favorite" DROP COLUMN IF EXISTS "__tmp";

-- Table: Payment
CREATE TABLE IF NOT EXISTS "Payment" (
    "__tmp" TEXT
);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "bookingId" TEXT NOT NULL;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "method" TEXT NOT NULL;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "transactionRef" TEXT NOT NULL;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "providerRef" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "escrowStatus" TEXT NOT NULL DEFAULT 'held';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "releasedAt" TIMESTAMP(3);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "refundedAt" TIMESTAMP(3);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Payment' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Payment" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Payment" DROP COLUMN IF EXISTS "__tmp";

-- Table: Payout
CREATE TABLE IF NOT EXISTS "Payout" (
    "__tmp" TEXT
);
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "method" TEXT NOT NULL;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "transactionRef" TEXT NOT NULL;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "providerRef" TEXT;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "failedReason" TEXT;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Payout' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Payout" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Payout" DROP COLUMN IF EXISTS "__tmp";

-- Table: Escrow
CREATE TABLE IF NOT EXISTS "Escrow" (
    "__tmp" TEXT
);
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "bookingId" TEXT NOT NULL;
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "paymentId" TEXT;
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL;
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'HELD';
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "releasedAt" TIMESTAMP(3);
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "providerUserId" TEXT NOT NULL;
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Escrow' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Escrow" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Escrow" DROP COLUMN IF EXISTS "__tmp";

-- Table: PlatformTransaction
CREATE TABLE IF NOT EXISTS "PlatformTransaction" (
    "__tmp" TEXT
);
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "bookingId" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "businessId" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "platformFee" DOUBLE PRECISION NOT NULL;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "providerAmount" DOUBLE PRECISION NOT NULL;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'KES';
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "escrowStatus" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "transactionId" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "metadata" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PlatformTransaction" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PlatformTransaction' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PlatformTransaction" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PlatformTransaction" DROP COLUMN IF EXISTS "__tmp";

-- Table: TransactionLog
CREATE TABLE IF NOT EXISTS "TransactionLog" (
    "__tmp" TEXT
);
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "bookingId" TEXT;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "provider" TEXT;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "referenceId" TEXT;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "metadata" TEXT;
ALTER TABLE "TransactionLog" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'TransactionLog' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "TransactionLog" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "TransactionLog" DROP COLUMN IF EXISTS "__tmp";

-- Table: Category
CREATE TABLE IF NOT EXISTS "Category" (
    "__tmp" TEXT
);
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "slug" TEXT NOT NULL;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "icon" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "parentId" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "serviceCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Category' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Category" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Category" DROP COLUMN IF EXISTS "__tmp";

-- Table: DiscountCode
CREATE TABLE IF NOT EXISTS "DiscountCode" (
    "__tmp" TEXT
);
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "code" TEXT NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "value" DOUBLE PRECISION NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "scope" TEXT NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "applicableIds" TEXT;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "minimumPurchase" DOUBLE PRECISION;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "maximumDiscount" DOUBLE PRECISION;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "usageLimit" INTEGER;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "usageCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "perUserLimit" INTEGER;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3) NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3) NOT NULL;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "DiscountCode" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'DiscountCode' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "DiscountCode" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "DiscountCode" DROP COLUMN IF EXISTS "__tmp";

-- Table: Conversation
CREATE TABLE IF NOT EXISTS "Conversation" (
    "__tmp" TEXT
);
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "participant1" TEXT NOT NULL;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "participant2" TEXT NOT NULL;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "lastMessage" TEXT;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "lastMessageAt" TIMESTAMP(3);
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Conversation' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Conversation" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Conversation" DROP COLUMN IF EXISTS "__tmp";

-- Table: ChatMessage
CREATE TABLE IF NOT EXISTS "ChatMessage" (
    "__tmp" TEXT
);
ALTER TABLE "ChatMessage" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "ChatMessage" ADD COLUMN IF NOT EXISTS "conversationId" TEXT NOT NULL;
ALTER TABLE "ChatMessage" ADD COLUMN IF NOT EXISTS "senderId" TEXT NOT NULL;
ALTER TABLE "ChatMessage" ADD COLUMN IF NOT EXISTS "content" TEXT NOT NULL;
ALTER TABLE "ChatMessage" ADD COLUMN IF NOT EXISTS "isRead" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ChatMessage" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'ChatMessage' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "ChatMessage" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "ChatMessage" DROP COLUMN IF EXISTS "__tmp";

-- Table: Message
CREATE TABLE IF NOT EXISTS "Message" (
    "__tmp" TEXT
);
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "conversationId" TEXT NOT NULL;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "senderId" TEXT NOT NULL;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "recipientId" TEXT NOT NULL;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "content" TEXT NOT NULL;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'TEXT';
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "attachmentUrl" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "isRead" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "readAt" TIMESTAMP(3);
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Message' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Message" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Message" DROP COLUMN IF EXISTS "__tmp";

-- Table: Notification
CREATE TABLE IF NOT EXISTS "Notification" (
    "__tmp" TEXT
);
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'info';
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "isRead" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "link" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Notification' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Notification" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Notification" DROP COLUMN IF EXISTS "__tmp";

-- Table: NotificationPreference
CREATE TABLE IF NOT EXISTS "NotificationPreference" (
    "__tmp" TEXT
);
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "pushEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "emailEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "smsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "bookingUpdates" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "messageNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "promotionNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "reviewNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "paymentNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "quietHoursStart" TEXT;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "quietHoursEnd" TEXT;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "NotificationPreference" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'NotificationPreference' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "NotificationPreference" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "NotificationPreference" DROP COLUMN IF EXISTS "__tmp";

-- Table: PushSubscription
CREATE TABLE IF NOT EXISTS "PushSubscription" (
    "__tmp" TEXT
);
ALTER TABLE "PushSubscription" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PushSubscription" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "PushSubscription" ADD COLUMN IF NOT EXISTS "endpoint" TEXT NOT NULL;
ALTER TABLE "PushSubscription" ADD COLUMN IF NOT EXISTS "authKey" TEXT NOT NULL;
ALTER TABLE "PushSubscription" ADD COLUMN IF NOT EXISTS "p256dhKey" TEXT NOT NULL;
ALTER TABLE "PushSubscription" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
ALTER TABLE "PushSubscription" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PushSubscription' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PushSubscription" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PushSubscription" DROP COLUMN IF EXISTS "__tmp";

-- Table: Wallet
CREATE TABLE IF NOT EXISTS "Wallet" (
    "__tmp" TEXT
);
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "balance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'KES';
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Wallet' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Wallet" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Wallet" DROP COLUMN IF EXISTS "__tmp";

-- Table: OTPVerification
CREATE TABLE IF NOT EXISTS "OTPVerification" (
    "__tmp" TEXT
);
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "code" TEXT NOT NULL;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "purpose" TEXT NOT NULL;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "verified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3) NOT NULL;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'OTPVerification' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "OTPVerification" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "OTPVerification" DROP COLUMN IF EXISTS "__tmp";

-- Table: PasswordReset
CREATE TABLE IF NOT EXISTS "PasswordReset" (
    "__tmp" TEXT
);
ALTER TABLE "PasswordReset" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PasswordReset" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "PasswordReset" ADD COLUMN IF NOT EXISTS "token" TEXT NOT NULL;
ALTER TABLE "PasswordReset" ADD COLUMN IF NOT EXISTS "used" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PasswordReset" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3) NOT NULL;
ALTER TABLE "PasswordReset" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PasswordReset' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PasswordReset" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PasswordReset" DROP COLUMN IF EXISTS "__tmp";

-- Table: EmailVerificationToken
CREATE TABLE IF NOT EXISTS "EmailVerificationToken" (
    "__tmp" TEXT
);
ALTER TABLE "EmailVerificationToken" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "EmailVerificationToken" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "EmailVerificationToken" ADD COLUMN IF NOT EXISTS "token" TEXT NOT NULL;
ALTER TABLE "EmailVerificationToken" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL;
ALTER TABLE "EmailVerificationToken" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3) NOT NULL;
ALTER TABLE "EmailVerificationToken" ADD COLUMN IF NOT EXISTS "isUsed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "EmailVerificationToken" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'EmailVerificationToken' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "EmailVerificationToken" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "EmailVerificationToken" DROP COLUMN IF EXISTS "__tmp";

-- Table: UserBan
CREATE TABLE IF NOT EXISTS "UserBan" (
    "__tmp" TEXT
);
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "userName" TEXT NOT NULL;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "userEmail" TEXT NOT NULL;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "bannedBy" TEXT;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "reason" TEXT NOT NULL;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'BAN';
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "isPermanent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3);
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "appealStatus" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "appealReason" TEXT;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "appealDate" TIMESTAMP(3);
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "appealResolvedAt" TIMESTAMP(3);
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "bannedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "UserBan" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'UserBan' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "UserBan" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "UserBan" DROP COLUMN IF EXISTS "__tmp";

-- Table: BlockedUser
CREATE TABLE IF NOT EXISTS "BlockedUser" (
    "__tmp" TEXT
);
ALTER TABLE "BlockedUser" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "BlockedUser" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "BlockedUser" ADD COLUMN IF NOT EXISTS "blockedId" TEXT NOT NULL;
ALTER TABLE "BlockedUser" ADD COLUMN IF NOT EXISTS "reason" TEXT;
ALTER TABLE "BlockedUser" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'BlockedUser' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "BlockedUser" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "BlockedUser" DROP COLUMN IF EXISTS "__tmp";

-- Table: Dispute
CREATE TABLE IF NOT EXISTS "Dispute" (
    "__tmp" TEXT
);
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'OPEN';
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "bookingId" TEXT NOT NULL;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "providerId" TEXT NOT NULL;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "customerId" TEXT NOT NULL;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "reason" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "resolution" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "evidence" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Dispute' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Dispute" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Dispute" DROP COLUMN IF EXISTS "__tmp";

-- Table: InsuranceClaim
CREATE TABLE IF NOT EXISTS "InsuranceClaim" (
    "__tmp" TEXT
);
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "claimNumber" TEXT NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "userType" TEXT NOT NULL DEFAULT 'customer';
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "customerName" TEXT NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "customerEmail" TEXT NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "providerId" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "providerName" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "businessId" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "businessName" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "bookingId" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'SUBMITTED';
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "documents" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "incidentDate" TIMESTAMP(3);
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "resolution" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "reviewedBy" TEXT;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3);
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "InsuranceClaim" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'InsuranceClaim' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "InsuranceClaim" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "InsuranceClaim" DROP COLUMN IF EXISTS "__tmp";

-- Table: AuditLog
CREATE TABLE IF NOT EXISTS "AuditLog" (
    "__tmp" TEXT
);
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "action" TEXT NOT NULL;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "resource" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "details" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'AuditLog' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "AuditLog" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "AuditLog" DROP COLUMN IF EXISTS "__tmp";

-- Table: SecurityAuditLog
CREATE TABLE IF NOT EXISTS "SecurityAuditLog" (
    "__tmp" TEXT
);
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "action" TEXT NOT NULL;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT NOT NULL;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "route" TEXT;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "method" TEXT;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "details" TEXT;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "success" BOOLEAN NOT NULL;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "requestId" TEXT NOT NULL;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "hash" TEXT NOT NULL;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "previousHash" TEXT;
ALTER TABLE "SecurityAuditLog" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'SecurityAuditLog' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "SecurityAuditLog" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "SecurityAuditLog" DROP COLUMN IF EXISTS "__tmp";

-- Table: SecurityAlert
CREATE TABLE IF NOT EXISTS "SecurityAlert" (
    "__tmp" TEXT
);
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "severity" TEXT NOT NULL;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT NOT NULL;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "metadata" TEXT;
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'OPEN';
ALTER TABLE "SecurityAlert" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'SecurityAlert' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "SecurityAlert" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "SecurityAlert" DROP COLUMN IF EXISTS "__tmp";

-- Table: MonitoringError
CREATE TABLE IF NOT EXISTS "MonitoringError" (
    "__tmp" TEXT
);
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "stack" TEXT;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "severity" TEXT NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "route" TEXT;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "method" TEXT;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "url" TEXT;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "resolved" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "resolvedAt" TIMESTAMP(3);
ALTER TABLE "MonitoringError" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'MonitoringError' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "MonitoringError" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "MonitoringError" DROP COLUMN IF EXISTS "__tmp";

-- Table: AdminReport
CREATE TABLE IF NOT EXISTS "AdminReport" (
    "__tmp" TEXT
);
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "reporterId" TEXT;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "reporterName" TEXT NOT NULL;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "reporterEmail" TEXT NOT NULL;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "reportedUserId" TEXT;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "reportedUserName" TEXT;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "reportedUserEmail" TEXT;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "reason" TEXT NOT NULL;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "evidence" TEXT;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "action" TEXT;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "resolvedAt" TIMESTAMP(3);
ALTER TABLE "AdminReport" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'AdminReport' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "AdminReport" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "AdminReport" DROP COLUMN IF EXISTS "__tmp";

-- Table: SupportTicket
CREATE TABLE IF NOT EXISTS "SupportTicket" (
    "__tmp" TEXT
);
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "userName" TEXT NOT NULL;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "userEmail" TEXT NOT NULL;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "subject" TEXT NOT NULL;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'GENERAL';
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "priority" TEXT NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'OPEN';
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "SupportTicket" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'SupportTicket' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "SupportTicket" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "SupportTicket" DROP COLUMN IF EXISTS "__tmp";

-- Table: TicketReply
CREATE TABLE IF NOT EXISTS "TicketReply" (
    "__tmp" TEXT
);
ALTER TABLE "TicketReply" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "TicketReply" ADD COLUMN IF NOT EXISTS "ticketId" TEXT NOT NULL;
ALTER TABLE "TicketReply" ADD COLUMN IF NOT EXISTS "from" TEXT NOT NULL;
ALTER TABLE "TicketReply" ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL;
ALTER TABLE "TicketReply" ADD COLUMN IF NOT EXISTS "adminName" TEXT;
ALTER TABLE "TicketReply" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'TicketReply' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "TicketReply" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "TicketReply" DROP COLUMN IF EXISTS "__tmp";

-- Table: FormSubmission
CREATE TABLE IF NOT EXISTS "FormSubmission" (
    "__tmp" TEXT
);
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "subject" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "metadata" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'FormSubmission' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "FormSubmission" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "FormSubmission" DROP COLUMN IF EXISTS "__tmp";

-- Table: WebhookEvent
CREATE TABLE IF NOT EXISTS "WebhookEvent" (
    "__tmp" TEXT
);
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "provider" TEXT NOT NULL;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "providerEventId" TEXT NOT NULL;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "eventType" TEXT NOT NULL;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'RECEIVED';
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "requestBody" TEXT NOT NULL;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "requestHeaders" TEXT;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "processingAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "lastAttemptAt" TIMESTAMP(3);
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "errorMessage" TEXT;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "processingTimeMs" INTEGER;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "responseCode" INTEGER;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "relatedPaymentId" TEXT;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "relatedBookingId" TEXT;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "signatureValid" BOOLEAN;
ALTER TABLE "WebhookEvent" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'WebhookEvent' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "WebhookEvent" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "WebhookEvent" DROP COLUMN IF EXISTS "__tmp";

-- Table: AnalyticsEvent
CREATE TABLE IF NOT EXISTS "AnalyticsEvent" (
    "__tmp" TEXT
);
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "event" TEXT NOT NULL;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "properties" TEXT;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "sessionId" TEXT NOT NULL;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "device" TEXT;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "page" TEXT;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "timestamp" TIMESTAMP(3) NOT NULL;
ALTER TABLE "AnalyticsEvent" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'AnalyticsEvent' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "AnalyticsEvent" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "AnalyticsEvent" DROP COLUMN IF EXISTS "__tmp";

-- Table: RateLimit
CREATE TABLE IF NOT EXISTS "RateLimit" (
    "__tmp" TEXT
);
ALTER TABLE "RateLimit" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "RateLimit" ADD COLUMN IF NOT EXISTS "key" TEXT NOT NULL;
ALTER TABLE "RateLimit" ADD COLUMN IF NOT EXISTS "count" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "RateLimit" ADD COLUMN IF NOT EXISTS "resetTime" TIMESTAMP(3) NOT NULL;
ALTER TABLE "RateLimit" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "RateLimit" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'RateLimit' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "RateLimit" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "RateLimit" DROP COLUMN IF EXISTS "__tmp";

-- Table: Media
CREATE TABLE IF NOT EXISTS "Media" (
    "__tmp" TEXT
);
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "url" TEXT NOT NULL;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'IMAGE';
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "publicId" TEXT;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "width" INTEGER;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "height" INTEGER;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "sizeBytes" INTEGER;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "format" TEXT;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "folder" TEXT NOT NULL DEFAULT 'general';
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Media' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Media" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Media" DROP COLUMN IF EXISTS "__tmp";

-- Table: TimeSlot
CREATE TABLE IF NOT EXISTS "TimeSlot" (
    "__tmp" TEXT
);
ALTER TABLE "TimeSlot" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "TimeSlot" ADD COLUMN IF NOT EXISTS "serviceId" TEXT NOT NULL;
ALTER TABLE "TimeSlot" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL;
ALTER TABLE "TimeSlot" ADD COLUMN IF NOT EXISTS "startTime" TEXT NOT NULL;
ALTER TABLE "TimeSlot" ADD COLUMN IF NOT EXISTS "endTime" TEXT NOT NULL;
ALTER TABLE "TimeSlot" ADD COLUMN IF NOT EXISTS "isBooked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TimeSlot" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'TimeSlot' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "TimeSlot" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "TimeSlot" DROP COLUMN IF EXISTS "__tmp";

-- Table: BlogArticle
CREATE TABLE IF NOT EXISTS "BlogArticle" (
    "__tmp" TEXT
);
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "slug" TEXT NOT NULL;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "excerpt" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "content" TEXT NOT NULL;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "featuredImage" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "tags" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "author" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "authorImage" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "authorId" TEXT;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "authorType" TEXT NOT NULL DEFAULT 'admin';
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "readTime" INTEGER;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "isPublished" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'BlogArticle' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "BlogArticle" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "BlogArticle" DROP COLUMN IF EXISTS "__tmp";

-- Table: BrandKit
CREATE TABLE IF NOT EXISTS "BrandKit" (
    "__tmp" TEXT
);
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "fileUrl" TEXT NOT NULL;
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "fileSize" INTEGER;
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "fileType" TEXT;
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "uploadedBy" TEXT;
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "BrandKit" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'BrandKit' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "BrandKit" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "BrandKit" DROP COLUMN IF EXISTS "__tmp";

-- Table: PressKit
CREATE TABLE IF NOT EXISTS "PressKit" (
    "__tmp" TEXT
);
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "fileUrl" TEXT NOT NULL;
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "fileSize" INTEGER;
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "fileType" TEXT;
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "uploadedBy" TEXT;
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PressKit" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PressKit' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PressKit" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PressKit" DROP COLUMN IF EXISTS "__tmp";

-- Table: PageContent
CREATE TABLE IF NOT EXISTS "PageContent" (
    "__tmp" TEXT
);
ALTER TABLE "PageContent" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PageContent" ADD COLUMN IF NOT EXISTS "page" TEXT NOT NULL;
ALTER TABLE "PageContent" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL;
ALTER TABLE "PageContent" ADD COLUMN IF NOT EXISTS "content" TEXT NOT NULL;
ALTER TABLE "PageContent" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;
ALTER TABLE "PageContent" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PageContent" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PageContent' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PageContent" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PageContent" DROP COLUMN IF EXISTS "__tmp";

-- Table: Promotion
CREATE TABLE IF NOT EXISTS "Promotion" (
    "__tmp" TEXT
);
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "businessName" TEXT NOT NULL;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3) NOT NULL;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3) NOT NULL;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "price" DOUBLE PRECISION NOT NULL;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "boostLevel" INTEGER;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "section" TEXT;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "channels" TEXT;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "targetAudience" TEXT;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "autoRenew" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "analytics" TEXT;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Promotion" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Promotion' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Promotion" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Promotion" DROP COLUMN IF EXISTS "__tmp";

-- Table: Advertisement
CREATE TABLE IF NOT EXISTS "Advertisement" (
    "__tmp" TEXT
);
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "businessId" TEXT;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "businessName" TEXT NOT NULL;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT NOT NULL;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "contactPhone" TEXT;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "package" TEXT NOT NULL;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "duration" INTEGER NOT NULL;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "budget" DOUBLE PRECISION NOT NULL;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3);
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3);
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "impressions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "clicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "conversions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Advertisement" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Advertisement' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Advertisement" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Advertisement" DROP COLUMN IF EXISTS "__tmp";

-- Table: PremiumListing
CREATE TABLE IF NOT EXISTS "PremiumListing" (
    "__tmp" TEXT
);
ALTER TABLE "PremiumListing" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PremiumListing" ADD COLUMN IF NOT EXISTS "businessId" TEXT NOT NULL;
ALTER TABLE "PremiumListing" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "PremiumListing" ADD COLUMN IF NOT EXISTS "plan" TEXT;
ALTER TABLE "PremiumListing" ADD COLUMN IF NOT EXISTS "price" DOUBLE PRECISION NOT NULL;
ALTER TABLE "PremiumListing" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3) NOT NULL;
ALTER TABLE "PremiumListing" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PremiumListing' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PremiumListing" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PremiumListing" DROP COLUMN IF EXISTS "__tmp";

-- Table: PlatformSetting
CREATE TABLE IF NOT EXISTS "PlatformSetting" (
    "__tmp" TEXT
);
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "key" TEXT NOT NULL;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "value" TEXT NOT NULL;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PlatformSetting' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "PlatformSetting" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "PlatformSetting" DROP COLUMN IF EXISTS "__tmp";

-- Table: FAQ
CREATE TABLE IF NOT EXISTS "FAQ" (
    "__tmp" TEXT
);
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "question" TEXT NOT NULL;
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "answer" TEXT NOT NULL;
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'general';
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "isPublished" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "FAQ" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'FAQ' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "FAQ" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "FAQ" DROP COLUMN IF EXISTS "__tmp";

-- Table: TeamMember
CREATE TABLE IF NOT EXISTS "TeamMember" (
    "__tmp" TEXT
);
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'TeamMember' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "TeamMember" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "TeamMember" DROP COLUMN IF EXISTS "__tmp";

-- Table: Job
CREATE TABLE IF NOT EXISTS "Job" (
    "__tmp" TEXT
);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "department" TEXT NOT NULL;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "location" TEXT NOT NULL DEFAULT 'Nairobi, Kenya';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'Full-time';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "requirements" TEXT NOT NULL;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'OPEN';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Job' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "Job" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "Job" DROP COLUMN IF EXISTS "__tmp";

-- Table: JobApplication
CREATE TABLE IF NOT EXISTS "JobApplication" (
    "__tmp" TEXT
);
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "jobId" TEXT NOT NULL;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "resume" TEXT;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "coverLetter" TEXT;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "JobApplication" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'JobApplication' AND constraint_type = 'PRIMARY KEY') THEN
        EXECUTE 'ALTER TABLE "JobApplication" ADD PRIMARY KEY ("id")';
    END IF;
END $do$;
ALTER TABLE "JobApplication" DROP COLUMN IF EXISTS "__tmp";

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX IF NOT EXISTS "Review_bookingId_key" ON "Review"("bookingId");
CREATE UNIQUE INDEX IF NOT EXISTS "Favorite_userId_businessId_key" ON "Favorite"("userId", "businessId");
CREATE UNIQUE INDEX IF NOT EXISTS "Payment_transactionRef_key" ON "Payment"("transactionRef");
CREATE UNIQUE INDEX IF NOT EXISTS "Payout_transactionRef_key" ON "Payout"("transactionRef");
CREATE UNIQUE INDEX IF NOT EXISTS "Category_slug_key" ON "Category"("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "DiscountCode_code_key" ON "DiscountCode"("code");
CREATE UNIQUE INDEX IF NOT EXISTS "NotificationPreference_userId_key" ON "NotificationPreference"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "PushSubscription_endpoint_key" ON "PushSubscription"("endpoint");
CREATE UNIQUE INDEX IF NOT EXISTS "Wallet_userId_key" ON "Wallet"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "PasswordReset_token_key" ON "PasswordReset"("token");
CREATE UNIQUE INDEX IF NOT EXISTS "EmailVerificationToken_token_key" ON "EmailVerificationToken"("token");
CREATE UNIQUE INDEX IF NOT EXISTS "UserBan_userId_key" ON "UserBan"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "BlockedUser_userId_blockedId_key" ON "BlockedUser"("userId", "blockedId");
CREATE UNIQUE INDEX IF NOT EXISTS "InsuranceClaim_claimNumber_key" ON "InsuranceClaim"("claimNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "WebhookEvent_provider_providerEventId_key" ON "WebhookEvent"("provider", "providerEventId");
CREATE UNIQUE INDEX IF NOT EXISTS "RateLimit_key_key" ON "RateLimit"("key");
CREATE UNIQUE INDEX IF NOT EXISTS "BlogArticle_slug_key" ON "BlogArticle"("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "PageContent_page_key" ON "PageContent"("page");
CREATE UNIQUE INDEX IF NOT EXISTS "PlatformSetting_key_key" ON "PlatformSetting"("key");

-- Foreign keys
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Business' AND constraint_name = 'Business_ownerId_fkey') THEN
        EXECUTE 'ALTER TABLE "Business" ADD CONSTRAINT "Business_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Service' AND constraint_name = 'Service_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "Service" ADD CONSTRAINT "Service_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Staff' AND constraint_name = 'Staff_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "Staff" ADD CONSTRAINT "Staff_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PortfolioItem' AND constraint_name = 'PortfolioItem_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "PortfolioItem" ADD CONSTRAINT "PortfolioItem_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Booking' AND constraint_name = 'Booking_customerId_fkey') THEN
        EXECUTE 'ALTER TABLE "Booking" ADD CONSTRAINT "Booking_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Booking' AND constraint_name = 'Booking_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "Booking" ADD CONSTRAINT "Booking_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Booking' AND constraint_name = 'Booking_serviceId_fkey') THEN
        EXECUTE 'ALTER TABLE "Booking" ADD CONSTRAINT "Booking_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE SET NULL ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Booking' AND constraint_name = 'Booking_staffId_fkey') THEN
        EXECUTE 'ALTER TABLE "Booking" ADD CONSTRAINT "Booking_staffId_fkey" FOREIGN KEY ("staffId") REFERENCES "Staff"("id") ON DELETE SET NULL ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Review' AND constraint_name = 'Review_bookingId_fkey') THEN
        EXECUTE 'ALTER TABLE "Review" ADD CONSTRAINT "Review_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Review' AND constraint_name = 'Review_customerId_fkey') THEN
        EXECUTE 'ALTER TABLE "Review" ADD CONSTRAINT "Review_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Review' AND constraint_name = 'Review_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "Review" ADD CONSTRAINT "Review_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Favorite' AND constraint_name = 'Favorite_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "Favorite" ADD CONSTRAINT "Favorite_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Favorite' AND constraint_name = 'Favorite_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "Favorite" ADD CONSTRAINT "Favorite_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Payment' AND constraint_name = 'Payment_bookingId_fkey') THEN
        EXECUTE 'ALTER TABLE "Payment" ADD CONSTRAINT "Payment_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Payment' AND constraint_name = 'Payment_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "Payment" ADD CONSTRAINT "Payment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Escrow' AND constraint_name = 'Escrow_bookingId_fkey') THEN
        EXECUTE 'ALTER TABLE "Escrow" ADD CONSTRAINT "Escrow_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Escrow' AND constraint_name = 'Escrow_paymentId_fkey') THEN
        EXECUTE 'ALTER TABLE "Escrow" ADD CONSTRAINT "Escrow_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE SET NULL ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Escrow' AND constraint_name = 'Escrow_providerUserId_fkey') THEN
        EXECUTE 'ALTER TABLE "Escrow" ADD CONSTRAINT "Escrow_providerUserId_fkey" FOREIGN KEY ("providerUserId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'DiscountCode' AND constraint_name = 'DiscountCode_createdBy_fkey') THEN
        EXECUTE 'ALTER TABLE "DiscountCode" ADD CONSTRAINT "DiscountCode_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "Business"("id") ON DELETE SET NULL ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Conversation' AND constraint_name = 'Conversation_participant1_fkey') THEN
        EXECUTE 'ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_participant1_fkey" FOREIGN KEY ("participant1") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Conversation' AND constraint_name = 'Conversation_participant2_fkey') THEN
        EXECUTE 'ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_participant2_fkey" FOREIGN KEY ("participant2") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'ChatMessage' AND constraint_name = 'ChatMessage_conversationId_fkey') THEN
        EXECUTE 'ALTER TABLE "ChatMessage" ADD CONSTRAINT "ChatMessage_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'ChatMessage' AND constraint_name = 'ChatMessage_senderId_fkey') THEN
        EXECUTE 'ALTER TABLE "ChatMessage" ADD CONSTRAINT "ChatMessage_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Notification' AND constraint_name = 'Notification_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'NotificationPreference' AND constraint_name = 'NotificationPreference_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PushSubscription' AND constraint_name = 'PushSubscription_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "PushSubscription" ADD CONSTRAINT "PushSubscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Wallet' AND constraint_name = 'Wallet_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "Wallet" ADD CONSTRAINT "Wallet_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'OTPVerification' AND constraint_name = 'OTPVerification_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "OTPVerification" ADD CONSTRAINT "OTPVerification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PasswordReset' AND constraint_name = 'PasswordReset_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "PasswordReset" ADD CONSTRAINT "PasswordReset_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'EmailVerificationToken' AND constraint_name = 'EmailVerificationToken_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "EmailVerificationToken" ADD CONSTRAINT "EmailVerificationToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'UserBan' AND constraint_name = 'UserBan_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "UserBan" ADD CONSTRAINT "UserBan_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'BlockedUser' AND constraint_name = 'BlockedUser_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "BlockedUser" ADD CONSTRAINT "BlockedUser_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'BlockedUser' AND constraint_name = 'BlockedUser_blockedId_fkey') THEN
        EXECUTE 'ALTER TABLE "BlockedUser" ADD CONSTRAINT "BlockedUser_blockedId_fkey" FOREIGN KEY ("blockedId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Dispute' AND constraint_name = 'Dispute_bookingId_fkey') THEN
        EXECUTE 'ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Dispute' AND constraint_name = 'Dispute_customerId_fkey') THEN
        EXECUTE 'ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Dispute' AND constraint_name = 'Dispute_providerId_fkey') THEN
        EXECUTE 'ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'InsuranceClaim' AND constraint_name = 'InsuranceClaim_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "InsuranceClaim" ADD CONSTRAINT "InsuranceClaim_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'SupportTicket' AND constraint_name = 'SupportTicket_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "SupportTicket" ADD CONSTRAINT "SupportTicket_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'TicketReply' AND constraint_name = 'TicketReply_ticketId_fkey') THEN
        EXECUTE 'ALTER TABLE "TicketReply" ADD CONSTRAINT "TicketReply_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "SupportTicket"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Media' AND constraint_name = 'Media_userId_fkey') THEN
        EXECUTE 'ALTER TABLE "Media" ADD CONSTRAINT "Media_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'TimeSlot' AND constraint_name = 'TimeSlot_serviceId_fkey') THEN
        EXECUTE 'ALTER TABLE "TimeSlot" ADD CONSTRAINT "TimeSlot_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Promotion' AND constraint_name = 'Promotion_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "Promotion" ADD CONSTRAINT "Promotion_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'Advertisement' AND constraint_name = 'Advertisement_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "Advertisement" ADD CONSTRAINT "Advertisement_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE SET NULL ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'PremiumListing' AND constraint_name = 'PremiumListing_businessId_fkey') THEN
        EXECUTE 'ALTER TABLE "PremiumListing" ADD CONSTRAINT "PremiumListing_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'JobApplication' AND constraint_name = 'JobApplication_jobId_fkey') THEN
        EXECUTE 'ALTER TABLE "JobApplication" ADD CONSTRAINT "JobApplication_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;';
    END IF;
END $do$;